---
- name: install
  shell: |
    curl -L http://toolbelt.treasuredata.com/sh/install-redhat.sh | sh
    /usr/lib64/fluent/ruby/bin/fluent-gem install fluent-plugin-elasticsearch
  args:
    creates: /etc/yum.repos.d/td.repo
  notify: restart fluentd

- name: allocate conf
  template: src=td-agent.conf dest=/etc/td-agent/
  notify: restart fluentd
